name: tugas_dari_ppt
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Sensors
  sensors_plus: ^4.0.2
  camera: ^0.10.5+7
  pdf: ^3.10.8
  printing: ^5.12.0
  
  # Date Formatting
  intl: ^0.19.0
  
  # UI Components (Optional - untuk icon tambahan)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true